### PR TITLE
Fix main and lambda snippet

### PR DESCRIPTION
**Pull request by damon-kwok**
@SeanTAllen 
Fix main and lambda snippet

### CODE REVIEW

**Comment by SeanTAllen** [comment]
merged. You are asking for a merge from your master branch. I believe you would be better off doing a branch per change. If you try to do multiple PRs, you'll need multiple branches. If you do a commit to a branch, open a PR and then push another change to that branch (for example master), it will become part of the open PR for that branch. Which probably isnt what you want in this case.

**Comment by damon-kwok** [comment]
i see.

**Comment by SeanTAllen** [comment]
@damon-kwok this might help some: https://github.com/ponylang/ponyc/blob/master/CONTRIBUTING.md#pull-request

**Comment by SeanTAllen** [comment]
thanks btw for your contributions! they are appreciated.

**Pull request merged**
